CREATE TABLE CADASTROCLIENTE(
  nucliente int IDENTITY (1,1) PRIMARY KEY,
  cpfoucnpj varchar(25) not null,
  tipo varchar(10) not null,
  nome varchar(100) not null,
  inscmunicipal varchar(20) not null,
  inscestadual varchar(20) not null,
  cep varchar(15) not null ,
  logradouro varchar(80) not null,
  cidade varchar(80) not null,
  estado varchar(80) not null,
  bairro varchar(80) not null,
  municipio varchar(80) not null,
  uf varchar(5) not null,
  complemento varchar(92),
  homepage varchar(100),
  telefone1 varchar(20) ,
  telefone2 varchar(20),
  contato varchar(80) ,
  email varchar(100) ,
  datacadastro date not null,
  observacao varchar(200),
  databloqueio date ,
  responsavelpelobloqueio varchar(80),
  justificativabloqueio varchar(200),
  status varchar(10),
  ultimaalteracao varchar(100) not null,
  dataultimaalteracao date not null,
  horaultimaalteracao time not null,

);