CREATE TABLE CONTRATO(
nucontrato int IDENTITY (1,1) PRIMARY KEY,
nuorcamento VARCHAR(200) not null,
tempoprevisto varchar(200) not null,
valorinvestimento real not null,
subtotal real not null,
retornoesperado real not null,
totaldespesa real not null,
valorfaturado real not null,
valorafaturar real not null,
percentuallucro decimal(7,2) not null,
percentualprejuizo decimal(7,2) not null,
cpfoucnpj varchar(25) not null,
idcliente int not null,
cliente varchar(100) not null,
inscmunicipal varchar(20) not null,
inscestadual varchar(20) not null,
telefone1 varchar(20) not null,
telefone2 varchar (20) not null,
email varchar(100) not null,
homepage varchar(100) not null,
responsavel varchar(200) not null,
cep varchar(15) not null,
logradouro varchar(80) not null,
nu varchar(5) not null,
bairro varchar(80) not null,
uf varchar(5) not null,
municipio varchar(80) not null,
complemento varchar(200) not null,
datainiciocontrato date not null,
dataprevistatermino date not null,
temporestante varchar(80) not null,
responsavelpelocontrato varchar(200) not null,
vendedor varchar(200) not null,
observacao varchar(500) not null,
ultimaalteracao varchar(100) not null,
dataalteracao date not null,
horaalteracao time not null,
)