CREATE TABLE FUNCIONARIO (
    registro int IDENTITY (1,1) PRIMARY KEY,
	nome varchar(200) not null,
	nascimento date not null,
	idade varchar(100) not null,
	sexo varchar(80) not null,
	cep varchar(40) not null,
	cidade varchar(100) not null,
	uf varchar(5) not null,
	logradouro varchar(100) not null,
	numero varchar(50) not null,
	bairro varchar(100) not null,
	telefone1 varchar(20),
	telefone2 varchar(20),
	pai varchar(200),
	mae varchar(200),
	numeroctps varchar(20) not null,
	seriectps varchar(20) not null,
	emissaoctps  date not null,
	numeroci varchar(30) not null,
	emissaoci date not null,
	numerocpf varchar(15) not null,
	nucnh varchar(15) not null,
	categoriacnh varchar(10) not null,
	validadecnh date,
	nucontabanco varchar(40) not null,
	dvcontabanco varchar(40) not null,
	nuagencia varchar(40) not null,
	banco varchar(90) not null,
	tipo varchar(40) not null,
	estadocivil varchar(40) not null,
	nacionalidade varchar(100) not null,
	nucontrato int not null,
	numeroopis varchar(60) not null,
	codlivroregistro varchar(200) not null,
	BRPDH varchar(80) not null, 
	nupagiregistro varchar(80) not null,
	orgaoexpeditor varchar(80) not null,
	nu_dependentes varchar(10) not null,
	numcertreservista varchar(40) not null,
	nuntiteleitor varchar(40) not null,
	escolaridade varchar(100) not null,
	ultimaalteracao varchar(100) not null,
	dataalteracao date not null,
	horaalteracao time not null,
	
);