CREATE TABLE ORCAMENTOCLIENTE(
nuorcamento int IDENTITY (1,1) PRIMARY KEY,
data date not null,
entregacliente date,
validade varchar(80) not null,
subtotal real not null,
desconto real not null,
total real not null,
cpfoucnpj varchar(25) not null,
cep varchar(15) not null,
logradouro varchar(80),
nu varchar(5) not null,
bairro varchar(80) not null,
uf varchar(5) not null,
municipio varchar(80) not null,
complemento varchar(200) not null,
responsavelenvioorcamento varchar(200) not null,
status varchar(200) not null,
justificativareprovacao varchar(200),
nucontrato int,
observacao varchar(200) ,
ultimaalteracao varchar(100) not null,
dataalteracao date not null,
horaalteracao time not null,
)